### ISSUE TITLE
[bug] Something went wrong: download_story() got an unexpected keyword argument 'is_overlay'

### ISSUE THREAD

**Issue by rabea98** [notcammy/PySnapStories#2]
I started getting this error on multiple users:

D:\PySnapStories-master>python pysnapstories.py sommerray

PYSNAPSTORIES (SCRIPT V2.1 - PYTHON V3.7.4) - 12:56:27 AM

Treating input as username. (no ID was detected)
Starting download for user: sommerray

Story Id     : sommerray
Story Title  : Sommer-Ray
Story amount : 6

Something went wrong: download_story() got an unexpected keyword argument 'is_overlay'
The script cannot continue, exiting.

**Comment by rabea98** [comment]
oh and the script doesn't seem to scrape stories from specific users.
one of the users is: "itsleah04"
Here's the log:
D:\PySnapStories-master>python pysnapstories.py itsleah04
-----------------------------------------------------------------------------------------------
PYSNAPSTORIES (SCRIPT V2.1 - PYTHON V3.7.4) - 12:58:59 AM
-----------------------------------------------------------------------------------------------
Treating input as username. (no ID was detected)
Starting download for user: itsleah04
-----------------------------------------------------------------------------------------------
The given username did not return any stories.
The script cannot continue, exiting.
--------------------------------------

**Comment by dvingerh** [comment]
I'll check it out later
Looks like snapchat is using two different endpoints for user stories now as well so in the meantime just manually get them from the endpoints. I recommend using extension like JSONView to make the response text readable and links clickable

https://search.snapchat.com/lookupStory?id=sommerray
https://storysharing.snapchat.com/v1/fetch/itsleah04?request_origin=ORIGIN_WEB_PLAYER

for the second endpoint if video has overlay change `embedded.mp4` to `media.mp4` in the url

**Comment by dvingerh** [comment]
Snapchat keeps changing the endpoints, right now both usernames return a valid response using the second one so its "fixed" in 747c4ae343788f78e53083438bee410c49bde37a

**Comment by rabea98** [comment]
Again, thanks for the quick fix
